#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zxing
Version  : 1.2.0
Release  : 1
URL      : https://github.com/nu-book/zxing-cpp/archive/refs/tags/v1.2.0.tar.gz
Source0  : https://github.com/nu-book/zxing-cpp/archive/refs/tags/v1.2.0.tar.gz
Summary  : ZXing library set
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: zxing-lib = %{version}-%{release}
Requires: zxing-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : glibc-dev
BuildRequires : pypi(pip)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtmultimedia-dev

%description
[![Build Status](https://github.com/nu-book/zxing-cpp/workflows/CI/badge.svg?branch=master)](https://github.com/nu-book/zxing-cpp/actions?query=workflow%3ACI)

%package dev
Summary: dev components for the zxing package.
Group: Development
Requires: zxing-lib = %{version}-%{release}
Provides: zxing-devel = %{version}-%{release}
Requires: zxing = %{version}-%{release}

%description dev
dev components for the zxing package.


%package lib
Summary: lib components for the zxing package.
Group: Libraries
Requires: zxing-license = %{version}-%{release}

%description lib
lib components for the zxing package.


%package license
Summary: license components for the zxing package.
Group: Default

%description license
license components for the zxing package.


%prep
%setup -q -n zxing-cpp-1.2.0
cd %{_builddir}/zxing-cpp-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649793120
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -DBUILD_EXAMPLES=OFF \
-DBUILD_BLACKBOX_TESTS=OFF
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1649793120
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zxing
cp %{_builddir}/zxing-cpp-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/zxing/669a1e53b9dd9df3474300d3d959bb85bad75945
cp %{_builddir}/zxing-cpp-1.2.0/LICENSE.Qt %{buildroot}/usr/share/package-licenses/zxing/b30087309fd6643085c94525ce63eed228bd266b
cp %{_builddir}/zxing-cpp-1.2.0/LICENSE.ZXing %{buildroot}/usr/share/package-licenses/zxing/a8f3e29d5eab4420318de979754f5637d4bf2c3f
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ZXing/BarcodeFormat.h
/usr/include/ZXing/BinaryBitmap.h
/usr/include/ZXing/BitArray.h
/usr/include/ZXing/BitHacks.h
/usr/include/ZXing/BitMatrix.h
/usr/include/ZXing/BitMatrixCursor.h
/usr/include/ZXing/BitMatrixIO.h
/usr/include/ZXing/BitSource.h
/usr/include/ZXing/ByteArray.h
/usr/include/ZXing/ByteMatrix.h
/usr/include/ZXing/CharacterSet.h
/usr/include/ZXing/CharacterSetECI.h
/usr/include/ZXing/ConcentricFinder.h
/usr/include/ZXing/CustomData.h
/usr/include/ZXing/DecodeHints.h
/usr/include/ZXing/DecodeStatus.h
/usr/include/ZXing/DecoderResult.h
/usr/include/ZXing/DetectorResult.h
/usr/include/ZXing/Flags.h
/usr/include/ZXing/GTIN.h
/usr/include/ZXing/GenericGF.h
/usr/include/ZXing/GenericGFPoly.h
/usr/include/ZXing/GenericLuminanceSource.h
/usr/include/ZXing/GlobalHistogramBinarizer.h
/usr/include/ZXing/GridSampler.h
/usr/include/ZXing/HybridBinarizer.h
/usr/include/ZXing/LogMatrix.h
/usr/include/ZXing/LuminanceSource.h
/usr/include/ZXing/Matrix.h
/usr/include/ZXing/MultiFormatReader.h
/usr/include/ZXing/MultiFormatWriter.h
/usr/include/ZXing/Pattern.h
/usr/include/ZXing/PerspectiveTransform.h
/usr/include/ZXing/Point.h
/usr/include/ZXing/Quadrilateral.h
/usr/include/ZXing/ReadBarcode.h
/usr/include/ZXing/Reader.h
/usr/include/ZXing/ReedSolomonDecoder.h
/usr/include/ZXing/ReedSolomonEncoder.h
/usr/include/ZXing/RegressionLine.h
/usr/include/ZXing/Result.h
/usr/include/ZXing/ResultMetadata.h
/usr/include/ZXing/ResultPoint.h
/usr/include/ZXing/Scope.h
/usr/include/ZXing/StructuredAppend.h
/usr/include/ZXing/TextDecoder.h
/usr/include/ZXing/TextEncoder.h
/usr/include/ZXing/TextUtfEncoding.h
/usr/include/ZXing/ThresholdBinarizer.h
/usr/include/ZXing/TritMatrix.h
/usr/include/ZXing/WhiteRectDetector.h
/usr/include/ZXing/ZXBigInteger.h
/usr/include/ZXing/ZXConfig.h
/usr/include/ZXing/ZXContainerAlgorithms.h
/usr/include/ZXing/ZXNullable.h
/usr/include/ZXing/ZXTestSupport.h
/usr/include/ZXing/ZXVersion.h
/usr/include/ZXing/aztec/AZDecoder.h
/usr/include/ZXing/aztec/AZDetector.h
/usr/include/ZXing/aztec/AZDetectorResult.h
/usr/include/ZXing/aztec/AZEncoder.h
/usr/include/ZXing/aztec/AZEncodingState.h
/usr/include/ZXing/aztec/AZHighLevelEncoder.h
/usr/include/ZXing/aztec/AZReader.h
/usr/include/ZXing/aztec/AZToken.h
/usr/include/ZXing/aztec/AZWriter.h
/usr/include/ZXing/datamatrix/DMBitLayout.h
/usr/include/ZXing/datamatrix/DMDataBlock.h
/usr/include/ZXing/datamatrix/DMDecoder.h
/usr/include/ZXing/datamatrix/DMDetector.h
/usr/include/ZXing/datamatrix/DMECEncoder.h
/usr/include/ZXing/datamatrix/DMEncoderContext.h
/usr/include/ZXing/datamatrix/DMHighLevelEncoder.h
/usr/include/ZXing/datamatrix/DMReader.h
/usr/include/ZXing/datamatrix/DMSymbolInfo.h
/usr/include/ZXing/datamatrix/DMSymbolShape.h
/usr/include/ZXing/datamatrix/DMVersion.h
/usr/include/ZXing/datamatrix/DMWriter.h
/usr/include/ZXing/maxicode/MCBitMatrixParser.h
/usr/include/ZXing/maxicode/MCDecoder.h
/usr/include/ZXing/maxicode/MCReader.h
/usr/include/ZXing/oned/ODCodabarReader.h
/usr/include/ZXing/oned/ODCodabarWriter.h
/usr/include/ZXing/oned/ODCode128Patterns.h
/usr/include/ZXing/oned/ODCode128Reader.h
/usr/include/ZXing/oned/ODCode128Writer.h
/usr/include/ZXing/oned/ODCode39Reader.h
/usr/include/ZXing/oned/ODCode39Writer.h
/usr/include/ZXing/oned/ODCode93Reader.h
/usr/include/ZXing/oned/ODCode93Writer.h
/usr/include/ZXing/oned/ODDataBarCommon.h
/usr/include/ZXing/oned/ODDataBarExpandedReader.h
/usr/include/ZXing/oned/ODDataBarReader.h
/usr/include/ZXing/oned/ODEAN13Writer.h
/usr/include/ZXing/oned/ODEAN8Writer.h
/usr/include/ZXing/oned/ODITFReader.h
/usr/include/ZXing/oned/ODITFWriter.h
/usr/include/ZXing/oned/ODMultiUPCEANReader.h
/usr/include/ZXing/oned/ODReader.h
/usr/include/ZXing/oned/ODRowReader.h
/usr/include/ZXing/oned/ODUPCAWriter.h
/usr/include/ZXing/oned/ODUPCEANCommon.h
/usr/include/ZXing/oned/ODUPCEWriter.h
/usr/include/ZXing/oned/ODWriterHelper.h
/usr/include/ZXing/oned/rss/ODRSSExpandedBinaryDecoder.h
/usr/include/ZXing/oned/rss/ODRSSFieldParser.h
/usr/include/ZXing/oned/rss/ODRSSGenericAppIdDecoder.h
/usr/include/ZXing/pdf417/PDFBarcodeMetadata.h
/usr/include/ZXing/pdf417/PDFBarcodeValue.h
/usr/include/ZXing/pdf417/PDFBoundingBox.h
/usr/include/ZXing/pdf417/PDFCodeword.h
/usr/include/ZXing/pdf417/PDFCodewordDecoder.h
/usr/include/ZXing/pdf417/PDFCompaction.h
/usr/include/ZXing/pdf417/PDFDecodedBitStreamParser.h
/usr/include/ZXing/pdf417/PDFDecoderResultExtra.h
/usr/include/ZXing/pdf417/PDFDetectionResult.h
/usr/include/ZXing/pdf417/PDFDetectionResultColumn.h
/usr/include/ZXing/pdf417/PDFDetector.h
/usr/include/ZXing/pdf417/PDFEncoder.h
/usr/include/ZXing/pdf417/PDFHighLevelEncoder.h
/usr/include/ZXing/pdf417/PDFModulusGF.h
/usr/include/ZXing/pdf417/PDFModulusPoly.h
/usr/include/ZXing/pdf417/PDFReader.h
/usr/include/ZXing/pdf417/PDFScanningDecoder.h
/usr/include/ZXing/pdf417/PDFWriter.h
/usr/include/ZXing/qrcode/QRBitMatrixParser.h
/usr/include/ZXing/qrcode/QRCodecMode.h
/usr/include/ZXing/qrcode/QRDataBlock.h
/usr/include/ZXing/qrcode/QRDataMask.h
/usr/include/ZXing/qrcode/QRDecoder.h
/usr/include/ZXing/qrcode/QRDecoderMetadata.h
/usr/include/ZXing/qrcode/QRDetector.h
/usr/include/ZXing/qrcode/QRECB.h
/usr/include/ZXing/qrcode/QREncodeResult.h
/usr/include/ZXing/qrcode/QREncoder.h
/usr/include/ZXing/qrcode/QRErrorCorrectionLevel.h
/usr/include/ZXing/qrcode/QRFormatInformation.h
/usr/include/ZXing/qrcode/QRMaskUtil.h
/usr/include/ZXing/qrcode/QRMatrixUtil.h
/usr/include/ZXing/qrcode/QRReader.h
/usr/include/ZXing/qrcode/QRVersion.h
/usr/include/ZXing/qrcode/QRWriter.h
/usr/include/ZXing/textcodec/Big5MapTable.h
/usr/include/ZXing/textcodec/Big5TextDecoder.h
/usr/include/ZXing/textcodec/Big5TextEncoder.h
/usr/include/ZXing/textcodec/GBTextDecoder.h
/usr/include/ZXing/textcodec/GBTextEncoder.h
/usr/include/ZXing/textcodec/JPTextDecoder.h
/usr/include/ZXing/textcodec/JPTextEncoder.h
/usr/include/ZXing/textcodec/KRHangulMapping.h
/usr/include/ZXing/textcodec/KRTextDecoder.h
/usr/include/ZXing/textcodec/KRTextEncoder.h
/usr/lib64/cmake/ZXing/ZXingConfig.cmake
/usr/lib64/cmake/ZXing/ZXingConfigVersion.cmake
/usr/lib64/cmake/ZXing/ZXingTargets-relwithdebinfo.cmake
/usr/lib64/cmake/ZXing/ZXingTargets.cmake
/usr/lib64/libZXing.so
/usr/lib64/pkgconfig/zxing.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libZXing.so.1
/usr/lib64/libZXing.so.1.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zxing/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/zxing/a8f3e29d5eab4420318de979754f5637d4bf2c3f
/usr/share/package-licenses/zxing/b30087309fd6643085c94525ce63eed228bd266b
